export const orbizGameTasks = {
  easy: [
    'Name 5 fruits.',
    'Name 5 animals.',
    'Name 5 colors.',
    'Name 5 vegetables.',
    'Name 5 countries.',
    'Name 5 drinks.',
    'Name 5 sports.',
    'Name 5 desserts.',
    'Name 5 school subjects.',
    'Name 5 cities.',
    'Name 5 body parts.',
    'Name 5 things you can wear.',
    'Name 5 items in the kitchen.',
    'Name 5 types of transport.',
    'Name 5 musical instruments.',
    'Name 5 things that are red.',
    'Name 5 things you do in the morning.',
    'Name 5 things that use electricity.',
    'Name 5 animals that live in water.',
    'Name 5 things you can buy in a supermarket.',
  ],
  medium: [
    'Name 4 European capitals.',
    'Name 4 emotions.',
    'Name 4 types of wild animals.',
    'Name 4 oceans or seas.',
    'Name 4 famous landmarks.',
    'Name 4 types of berries.',
    'Name 4 languages spoken in Europe.',
    'Name 4 professions that work at night.',
    'Name 4 things that fly.',
    'Name 4 things you can recycle.',
    'Name 4 cold countries.',
    'Name 4 things that are round.',
    'Name 4 musical genres.',
    'Name 4 planets in the solar system.',
    'Name 4 things that are yellow.',
    'Name 4 types of drinks you can order in a café.',
    'Name 4 hobbies people do alone.',
    'Name 4 creatures from mythology.',
    'Name 4 famous movie characters.',
    'Name 4 things that melt.',
  ],
  hard: [
    'Name 3 chemical elements.',
    'Name 3 rivers in Europe.',
    'Name 3 inventions that changed the world.',
    'Name 3 endangered animals.',
    'Name 3 Nobel Prize winners.',
    'Name 3 constellations.',
    'Name 3 historical battles.',
    'Name 3 famous painters.',
    'Name 3 programming languages.',
    'Name 3 mountain ranges.',
    'Name 3 philosophical concepts.',
    'Name 3 classical composers.',
    'Name 3 rare weather phenomena.',
    'Name 3 countries that no longer exist.',
    'Name 3 famous scientists.',
    'Name 3 types of renewable energy.',
    'Name 3 architectural styles.',
    'Name 3 book genres for adults.',
    'Name 3 diseases from history.',
    'Name 3 world religions.',
  ],
};
